POST http://127.0.0.1:1234/test/run
Content-Type: application/json


# # == Case 1 ==
# {
#   "ratePerSecond": 2,
#   "testCount": 10,
#   "processingTimeMillis": 1000
#   "ratePerSecond": 11,
#   "testCount": 1200
# }

# # == Case 2 ==
# {
#   "ratePerSecond": 2,
#   "testCount": 100,
#   "processingTimeMillis": 60000
# }

# == Case 3 ==
# {
#   "ratePerSecond": 2,
#   "testCount": 500,
#   "processingTimeMillis": 60000
# }
